### ISSUE TITLE
Accept more Inputs

### ISSUE THREAD

**Issue by wcarllWRLD** [FB-18-19-PreAP-CS/math-helper-Christian-Cormier#9]
When A formula is selected, it asks do you want to continue. If the input is anything but "no", the Function continues. This can be frustrating for the user if they do not default to typing 'no', making it difficult to exit the Function. My suggestion is to allow the user to Input more versions of "no", such as "No", and "NO", and ask for the user to input "No".

**Comment by Christian-Cormier** [comment]
fixed by adding .lower()
